name: Check Code Quality

on:
  push:
    branches:
      - '!dependabot/**'

jobs:
  check-code:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Install dependencies
        run: yarn
      -
        name: Check ESLint
        run: yarn eslint:check
      -
        name: Check StyleLint
        run: yarn stylelint:check
      -
        name: Check Types
        run: yarn types:check
      -
        name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: yarn test:coverage
          debug: true
