name: Deploy (Production)

on:
  workflow_dispatch:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Deploy script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VDS_HOST }}
          username: ${{ secrets.VDS_USER }}
          password: ${{ secrets.VDS_PASSWORD }}
          port: ${{ secrets.VDS_PORT }}
          script: docker stop $(docker ps -a -q) && docker system prune --force && docker pull cherkasik/rdga-web:latest && docker run -d -p 81:80 cherkasik/rdga-web:latest