name: Push+Deploy (Production)

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build-push:
    uses: IlyaCherkasov/disc-golf-react/.github/workflows/push.yml@master
    secrets:
      DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  deploy:
    needs: build-push
    uses: IlyaCherkasov/disc-golf-react/.github/workflows/deploy.yml@master
    secrets:
      VDS_HOST: ${{ secrets.VDS_HOST }}
      VDS_USER: ${{ secrets.VDS_USER }}
      VDS_PASSWORD: ${{ secrets.VDS_PASSWORD }}
      VDS_PORT: ${{ secrets.VDS_PORT }}